### ISSUE TITLE
[1.12.2]Monsters drop their loot twice.

### ISSUE THREAD

**Issue by dragon3025** [ganymedes01/Headcrumbs#101]
Mod Version: Headcrumbs-1.12.2-2.0.4.12
Forge Version: 14.23.2.2611

I've noticed that loot is dropping twice from mobs. I tested it it with just this mod, and an Elder guardian drops 2 separate sponges. I'm noticing this from other mobs also.

**Comment by TheTurkeyDev** [comment]
If you remove the mod does this still happen?

**Comment by SteveKnowless** [comment]
@dragon3025 I also am having this same issue on my server

Mod Version: Headcrumbs-1.12.2-2.0.4.12
Forge Version: 14.23.2.2611

@Turkey2349 My server has over 100 mods and I have been troubleshooting this issue for a couple days now. I went through and added the mods one by one to see what was going on. I was able to conclude that it was the Headcrumbs mod. I was able to reproduce this in SP also. The best method I found was to spawn in several skeletons and wait until one dropped a bow. With head crumbs installed they always drop 2 bows. When I remove headcrumbs, back down to 1 bow. I can also tell you that this does not affect just mobs as I have seen it duplicate Tinkers Tools as well as Jetpacks on players deaths. 
To make sure that there was no conflicts with the other mods I had installed, I went and created a game with only headcrumbs and JEI installed. This issue still happened and 2 bows dropped. I hope this helps. Thanks

**Comment by cjburkey01** [comment]
Experiencing this as well with Forge 14.23.2.2624 and Headcrumbs 1.12.2-2.0.4.12. Happens for most mobs: zombies, skeletons, spiders, chickens, cows, and other mod's mobs too.

**Comment by TheTurkeyDev** [comment]
Issue has been fixed locally. Should have a build out in the next day or two

**Comment by SteveKnowless** [comment]
@Turkey2349 Awesome! You are the best

**Comment by cjburkey01** [comment]
Wow! Quickest mod developer response ever, thank you!

**Comment by TheTurkeyDev** [comment]
New build was just uploaded to curse. Please close this one you have verified the issue has been fixed!

**Comment by SteveKnowless** [comment]
@Turkey2349 Issue fixed in 2.0.4.14 Thanks
