### ISSUE TITLE
MANY Heads

### ISSUE THREAD

**Issue by Moobien** [ganymedes01/Headcrumbs#102]
Every creative tab is being spammed with heads.

**Comment by TheTurkeyDev** [comment]
This was fixed in the latest version

**Comment by Moobien** [comment]
Cool :) will update in the morning. Side note, how do I make the spawns considerably less common?

**Comment by TheTurkeyDev** [comment]
Within the mod it cannot be done, but there may be a mod that lets you change the spawn rates of mobs.
