### ISSUE TITLE
Invisible headcrumbs mobs

### ISSUE THREAD

**Issue by ZeWolfTah** [ganymedes01/Headcrumbs#103]
Forge version: 14.23.2.2623
Java version: 1.8.0_161 x64
Headcrumbs version: Headcrumbs-1.12.2-2.0.4.12

I'm playing on singleplayer, and sometimes headcrumbs mobs will spawn 100% invisible and be able to hit me unless I re-log into my world. I am unable to hit the mob back. I went into my logs to see if anything happened around that time, and found this:
https://pastebin.com/fT5w9Q9Y

It appears sometimes headcrumbs will fail to grab the skin from the mojang servers and will generate an invisible mob. The issue has been encountered several times now.
I have just now upgraded my headcrumbs to version 1.12.2-2.0.4.14 which was released 4 hours ago, but the issue isn't addressed in the change log, so I will post a new full log next time I encounter the issue.

**Comment by TheTurkeyDev** [comment]
That error occurs even without headcrumbs, so I don't believe it's due to head crumbs and it doesn't affect the load in of the skins. I will still look into the issue though.

**Comment by ZeWolfTah** [comment]
Line 7 of the paste says
at ganymedes01.headcrumbs.utils.ThreadedProfileFiller$1.run(ThreadedProfileFiller.java:25) [ThreadedProfileFiller$1.class:?]
which mentions headcrumbs, so I assumed it was probably related to what was going on. I'll try to gather a more relevant log file next time I see the error happen.

**Comment by SteveKnowless** [comment]
@ZeWolfTah are you playing with any other mods that modify mobs? Like Primitive Mobs or Lost Cities \ Lost Souls. I see this in my world also and after some research I found that it was intended because the mobs spawn with an invisibility buff, and sometimes only their sword can be seen or sometimes nothing at all because they have that buff.

**Comment by ZeWolfTah** [comment]
The invisible mobs don't even provide particles or show a held item/armor. The only mods I have that affect or add mobs are Headcrumbs, MCA, Millénaire, and recently EnderZoo but the issue was happening prior to me adding MCA or EnderZoo and still happens after adding them. It doesn't happen too often, I've only encountered it about 4 maybe 5 times since making this world about a week ago. But when it does happen it's quite annoying to be attacked by a mob I can't see or even hit back unless I re-log or change dimensions and come back.
Edit: Thermal Expansion also adds a few mobs and Twilight Forest also adds some, forgot to mention those. The bug has only been encountered while randomly navigating the overworld (mining, exploring the surface, talking to Millénaire villagers, etc)

**Comment by SteveKnowless** [comment]
Gotcha. I am sure that is annoying. Just wanted to make sure you were able to look at it and see if something else was causing it because I know it was a little annoying for me too until i found out it was intended. Good luck

**Comment by Sandriell** [comment]
I have this issue as well, and the only mobs it ever happens to is headcrumbs' mobs.

They are not enchanted-invisible, they are glitched-invisible. Cannot be hit back or interacted with in anyway by me the player. I have to get an npc guard from Ancient Warfare or Minecolonies to kill them for me.

**Comment by Sandriell** [comment]
Is it possible this is related? https://github.com/MinecraftForge/MinecraftForge/issues/4406

**Comment by DrEthan77** [comment]
this happens to me aswell

**Comment by TheTurkeyDev** [comment]
Cleaning out issues. If this issue still persists, please reopen.
