### ISSUE TITLE
I crash if i die by fire. [1.12.2]

### ISSUE THREAD

**Issue by gary-conlon** [ganymedes01/Headcrumbs#105]
I use VanillaFix and it said after i died by fire damage that i crashed due to HeadCrumbs. 
Here is the log and crash report.
Log - https://hastebin.com/wutexiwote.sql
Crash Report - https://hastebin.com/uguyonirad.rb

**Comment by TheTurkeyDev** [comment]
Ill look into it

**Comment by TheTurkeyDev** [comment]
New build should be out later today
