### ISSUE TITLE
Unable to connect to forge server (Fatally missing registry entries) when changing config of mod. [1.12.2]

### ISSUE THREAD

**Issue by noamsm** [ganymedes01/Headcrumbs#107]
Hi,
I'm creating a modpack that contains this mod in it. I'm now working on a server package for the pack.
I've ran into a problem while trying to add this mod to the server. If I add this mod to the server then no client is able to connect to it. If I try to connect then this is the error message I get:
![msfatally](https://user-images.githubusercontent.com/19357208/45372850-9a4b2b80-b5f6-11e8-97d1-362bae6f2521.PNG)

I have changed some names in the config of the mod, but I've made sure that the client and the server have the same config files and the mod does work client side.

P.S.
I've already looked at the log file, it doesn't contain anything...

**Comment by kreezxil** [comment]
I think this is related, there is no crash report to speak of.

In regards to a server pack. If the server pack is run in on a Windows machine headcrumbs will not cause a FATALLY MISSING REGISTRY ENTRIES error. If it is run on a Linux machine it will do it everytime.

I seem to recall that config values can cause the issue too which is what the opening post here is saying.
My heads config:
```json
heads {
    # Other mods can add usernames using inter-mod communications, turns this config to false will prevent that from happening
    B:"Enable usernames sent by other mods"=true
    S:forgeCraft <
        Tr4shM0nk3y
     >
    S:ftb <
        Darkosto
     >
    S:hermitcraft <
        Pure_Stone9
     >
    S:mindCrack <
        theripsaw666
     >
    S:modders <
        Kreezxil
        draekeaur
     >
    S:mojang <
        TheAmazingHaru
     >
    S:others <
        kehaan
        KTev_
        Hirschney
        Soluria
     >
    S:technic <
        Red_Fog
        Starvilia
        VapegodSpartini
        RayeArt
        S0ul0fTh3H3r0
     >
    S:youtubers <
        direwolf20
     >
}
```
It could be an issue with either resolving to get those skins with how Linux handles that vs Windows.
I'm going to now try with Enable Usernams sent .. disabled and just have it everything from mojang and see if that resolves it.

<theatrical pause>

ok, that solved nothing and probably made it worse. I disabed the usernames sent by other mods and suddenly config regenerated with lots and lots of names.

http://paste.ubuntu.com/p/TDW2vZ2zQm/

and I"m still getting Fatally Missing Registries. Really needed this to behave on a Linux box. :(

**Comment by TheTurkeyDev** [comment]
See #104
