### ISSUE TITLE
Headcrumbs 1.12.2 Version 2.0.4.15 have many Bugs.

### ISSUE THREAD

**Issue by Titoo8899** [ganymedes01/Headcrumbs#108]
In the newest version give it many bugs. 
1. No Heads loads the texture of animals
2. Then you place a head in the Headslot and will z.b. a Pighead on the head place it work not

- Please fix this why your mod work with this update not and the textures and so works not is a critical 
  bug for your mod!!!

**Comment by TheTurkeyDev** [comment]
Unfortunately Item rendering changed in 1.12, to a way that doesn't natively allow for custom item rending. As such I cannot have the heads show correctly in the inventory. I am actively looking for a solution, but do to my real life obligations, I do not have a ton of time to do much besides upkeep the mod.

**Comment by Titoo8899** [comment]
Okay, but the Heads on the Head Slot bug is then the only bug in the game. Then you Place a head on the player head slot then work the head not you can not see the head. Please fix this!!!

**Comment by TheTurkeyDev** [comment]
I will look into this and try to get that working again. Please next time be less demanding in your requests.

**Comment by Lykrast** [comment]
On the inventory icons part, [this](https://mcforge.readthedocs.io/en/latest/rendering/teisr/) looks to be a potential answer.

**Comment by TheTurkeyDev** [comment]
@Lykrast Yes I just found that the other day and am working on implementing it

**Comment by TheTurkeyDev** [comment]
Fixed in the latest version!
