### ISSUE TITLE
User Cache UUID issue

### ISSUE THREAD

**Issue by jadedcat** [ganymedes01/Headcrumbs#11]
https://www.dropbox.com/s/04y2abtj22i9acv/usercache.json?dl=0

appears to be causing this: 

http://pastebin.com/7BDPFhXh in Mage Quest for some users.

removing :"PurpleMentat","uuid":"848d057b-854a-4c89-bf45-74271b70e036","expiresOn":"2014-11-06 23:40:01 -0800"}] seems to fix it for some people.

Forum thread for topic:

http://forum.feed-the-beast.com/threads/ftb-mage-quest-alpha-bug-reports.51204/page-2#post-785444

**Comment by mjevans** [comment]
This is where you should be using some form of message passing construct to have a single writer thread and append to it's work queue (which is where the thread synchronization is implemented).

**Comment by ganymedes01** [comment]
I'm not the one who writes the usercache file so I can't change the way it's written (well, I could coremod it, but I'd rather not)
