### ISSUE TITLE
Celebrities are spawning in mushroom island biomes

### ISSUE THREAD

**Issue by Ephys** [ganymedes01/Headcrumbs#27]
Mushroom island (and island shore) biomes are peaceful biomes, however the celebrities which are somewhat aggressive mobs are spawning there. And as they're the only mobs allowed to spawn there, they're spawning massively (even with the probability set to 1).

Would you be so kind as to blacklist them from that biome ?
Thank you ~

**Comment by ganymedes01** [comment]
That's weird. I coded it specifically so it wouldn't spawn in mushroom islands/shores. Are you using a biomes mod?

**Comment by Ephys** [comment]
Biomes o' plenty but I don't think it overwrites the mushroom island

**Comment by ganymedes01** [comment]
Makes sense!

**Comment by ganymedes01** [comment]
Changed it around, mind having a look at it now and telling me what you think?

**Comment by Ephys** [comment]
I believe that should work, if you've got a jenkins I can go test that on my world and confirm it :)

**Comment by ganymedes01** [comment]
https://dl.dropboxusercontent.com/u/213747910/Headcrumbs-1.3.2.jar

**Comment by Ephys** [comment]
It resulted in a NPE when I tried to launch Minecraft:
http://pastebin.com/ExHCWhF2

Took a look at the source code of BiomeDictionnary, it's the biome passed to getTypesForBiome that is null as BiomeGenBase.getBiomeGenArray() is a stupid array and not a list ^^'.

**Comment by ganymedes01** [comment]
of course... silly me

**Comment by Ephys** [comment]
It's fixed, thank you :)

**Comment by ganymedes01** [comment]
Awesome! You can use that version, it should be pretty stable.
I did some re-writing of some core features (just to make them neater and easier to expand on), added hermitcraft members and Primitive Mobs heads.
