### ISSUE TITLE
Add technic staff.

### ISSUE THREAD

**Issue by bochen415** [ganymedes01/Headcrumbs#29]
As title

I would be a great honour for many technic users to be chased or slaughtered by the staff, that would also be a perfect way to integrate the communities.
The bad part is I don't know their IGNs.

**Comment by ganymedes01** [comment]
Any way you can find their IGNs?
I don't know much about technic, so I wouldn't know who their staff are even if their names were written in front of me (quite literally).

**Comment by ganymedes01** [comment]
If you give me their "names" (by that I mean whatever they are known as) I can try to find the IGNs myself. Just gimme a list to work with :3

**Comment by bochen415** [comment]
Hey @CannibalVox @GenPage @sct come on over here for a minute.
If this doesn't work I'll try their irc channel.

**Comment by GenPage** [comment]
IGN: GenPage

I would also recommend possibly integrating the names into a config system, you can package "default" lists but allows users to add their own.

**Comment by CannibalVox** [comment]
IGN: Slink730

**Comment by ganymedes01** [comment]
Thanks:3
The lists are purely symbolic though, they are just used to separate the sheer amount of names that the mod comes with by default. It doesn't change anything in game, so it doesn't make much sense to allow new lists to be added.
Users could simply shove all the default names into "others" and then add their names into "mindcrack", it wouldn't make a difference:3

**Comment by CannibalVox** [comment]
sct's IGN is: sct

**Comment by bochen415** [comment]
Hey, where's KakerMix?

**Comment by CannibalVox** [comment]
Kakermix's IGN is: Kakermix

**Comment by ganymedes01** [comment]
KakerMix has a skin but Kakermix doesn't

**Comment by CannibalVox** [comment]
That is probably the right thing then

**Comment by bochen415** [comment]
His profile on the forums has the IGN filled. "KakerMix"

**Comment by bochen415** [comment]
I leave you guys with this ticket. The staff will surely handle this better than me.
I don't know how recent are the information but I leave this for reference:
http://www.technicpack.net/about-us

**Comment by ganymedes01** [comment]
Their drawings disturb me deeply.

**Comment by CannibalVox** [comment]
One more: SKuli_Steinulf is Skuli.  That's the last guy.  Thanks so much!

**Comment by ganymedes01** [comment]
Done:3

**Comment by bochen415** [comment]
Wait, I see some inconsistency
SKuli_Steinulf
Skuli_Steinulf
k vs K
will this work?

**Comment by ganymedes01** [comment]
It's k not K :3

**Comment by bochen415** [comment]
kk

**Comment by CannibalVox** [comment]
Talonos is Talonos.  I'm a jerk and forgot to mention that.  :\ Sorry.

**Comment by ganymedes01** [comment]
No problem:3 The more names the merrier :D
