### ISSUE TITLE
Add way to allow more celebrities to be added

### ISSUE THREAD

**Issue by Parker8283** [ganymedes01/Headcrumbs#30]
Whether through an API of some sorts for a mod to add people (IMC, interfaces, etc), or though a list in the configs so that pack makers can add people (or both :D), this would be quite nice to have! :)

**Comment by Parker8283** [comment]
ok, so nevermind the config thing, I just saw it. But way for mods to add celebs?

**Comment by ganymedes01** [comment]
Easy-peasy. What do you think of a simple IMC containing a string with the desired username?

**Comment by Parker8283** [comment]
:D I will abuse this :P
