### ISSUE TITLE
[feature request] Disable the "Human" version of actual players

### ISSUE THREAD

**Issue by Ephys** [ganymedes01/Headcrumbs#36]
It's a bit weird to see yourself as an entity so it would be nice to have yourself removed from the list if you're in the list of celebrities but also play on a server with Headcrumbs.

Not that it bothers me specifically, I don't play with anyone on that list. /o/

**Comment by Lunatrius** [comment]
```
    # This prefix will be shown in front of celebrities names in-world. Meant to be used to differentiate celebrities from real players.
    S:prefix=Cloned
```

**Comment by ganymedes01** [comment]
What lunatrius said :3
