### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SgtPunishment** [ganymedes01/Headcrumbs#38]
How to get on the modders list? (Soul Shards: The Old Ways & Roadblocks)

**Comment by ganymedes01** [comment]
Send a PR :3

You can add your mc name [here] (https://github.com/ganymedes01/Headcrumbs/blob/master/src/main/java/ganymedes01/headcrumbs/Headcrumbs.java#L102), and your mod [here] (https://github.com/ganymedes01/Headcrumbs/blob/master/src/main/java/ganymedes01/headcrumbs/libs/CelebrityMap.java#L98) (choose one, I'm only adding one phrase per name)

**Comment by SgtPunishment** [comment]
Sweet, I might have to do that! Thanks!

**Comment by SgtPunishment** [comment]
Forgot to ask, is it Mod Name or Mod ID?

**Comment by ganymedes01** [comment]
Name :)
