### ISSUE TITLE
Illegal characters in names

### ISSUE THREAD

**Issue by Claycorp** [ganymedes01/Headcrumbs#41]
If you put in something that isn't allowed the game will crash and make the world unplayable until headcrumbs is removed.

Removal or replacing with a default would fix the issue. 

http://pastebin.com/Ci5VTpzr

**Comment by ganymedes01** [comment]
I can add a warning and remove illegal names but in the mean time... maybe just don't use illegal characters? XD

**Comment by Claycorp** [comment]
Yeah that would make sense but You can't always rely on others to do so. We have a mod that lets streamers set up things to happen to them when someone subs or donates and if they put in something it causes lots of problems as its done on the fly.

Just gave you a heads up about it and as many people use headcrumbs for the heads/statues it would be great if it can get fixed.

**Comment by Claycorp** [comment]
Something was added on our side also no need to worry about this. :P
