### ISSUE TITLE
Celebrities In The Outer Lands

### ISSUE THREAD

**Issue by natedogith1** [ganymedes01/Headcrumbs#42]
By default Celebrities will spawn in thaumcraft's added dimension(The Outer Lands). This is particularly an issue as Celebrities can pick up items, and this dimension generates with some non-despawnable items on the ground.

Personally, if possible, I'd like to see the spawning checking of Celebrities being bound to zombies (or some other entity), so that if a zombie couldn't spawn somewhere a Celebrity couldn't either. I feel this would handle a lot of cases where Celebrities shouldn't be spawning but are.

**Comment by ganymedes01** [comment]
You can blacklist which dimension they are allowed to spawn in :)

**Comment by natedogith1** [comment]
We can indeed blacklist certain dimensions (which I'm really glad was added, there use to be far to many in the end). However I've noticed that we don't need to blacklist them in the twilight forest or the erebus, you have those hard-coded in. I figured thaumcraft's outer lands should probably be added to that hard-coded list.

**Comment by ganymedes01** [comment]
Makes sense.
I don't have access to the code atm and forgot about my hardcoded blacklist. I shall add the TC's dimension to it when I'm back home
