### ISSUE TITLE
Crash with creative mode menu - Infinity Modpack v 1.6.2

### ISSUE THREAD

**Issue by SamRaven2** [ganymedes01/Headcrumbs#43]
http://paste.ee/p/IZbpA

Crash occurs when attempting to access the third page of the creative inventory menu. 

Using the 1.6.2 version of the FTB Infinity Modpack
Version 1.5.2 of Headcrumbs
Forge Build 10.13.3.1408

Crash also occurs using version 1.5.3 of Headcrumbs

**Comment by ganymedes01** [comment]
I'll look into it when I get home on sunday :)

**Comment by SamRaven2** [comment]
Cool, I should probably note that it does not crash if Headcrumbs is the only mod installed.
