### ISSUE TITLE
Command /give @p skull corrupts save folder

### ISSUE THREAD

**Issue by Lyl4c** [ganymedes01/Headcrumbs#46]
Crash Report: http://pastebin.com/1xh9yGuJ

I tried putting in this into a command block and soon after it corrupted my save world.
The command works just fine in vanilla 1.7.10

/give @p skull 1 3 {display:{Name:"Cardboard Box"},SkullOwner:{Id:"6ddf0ec2-23a0-415a-9591-5c9e3b6ea701",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWViYmZlMTY5YjZmZmY0OGNjYjA2ZTc5NDU5NTMzNjliZjRkYTY0ODZmYzI3YWY5MDMzNjg2Y2Q0OTBkMWQzIn19fQ=="}]}}}

**Comment by ganymedes01** [comment]
Whoops.
Seems to be because the profile the skull was created with doesn't have a defined name.

You should use:
/headcrumbs <player that will get the head> <player that will be on the head>

**Comment by ganymedes01** [comment]
I recommend that you build a custom version of the mod for yourself and delete the corrupted stack.

- Download the project and unzip it into a folder
- Inside that folder create a folder called "libs" and place inside of it a jar of each of the following: NotEnoughItems, LycanitesMobs, Thaumcraft
- Hold shift and right click on the folder and open the command prompt
-Run this command: gradlew.bat build

After some time (can take a while if your internet is slow) a "build" folder will appear inside the folder you created, and inside it a "libs" folder, inside that folder you'll find the jar you've built :3

**Comment by Lyl4c** [comment]
Sweet! The command works now. Thanks, and it was a small testing world so luckily this was fixed before someone else lost theirs.

That command was generated by freshcoal.com which takes the skin of a player and converts it into a string to use for a custom head just like this one. It might be possible to use this in reverse? Fresh Coal indeed has some amazing custom heads that I can't use for Headcrumbs. TnT
