### ISSUE TITLE
Headcrumbs Mobs Spawn too Frequently in Tainted Land

### ISSUE THREAD

**Issue by shadowfacts** [ganymedes01/Headcrumbs#47]
In the Tainted Land biome from Thaumcraft, Headcrumbs mobs spawn way too frequently. My guess is this is because normal mobs don't spawn in that biome.

**Side Note:** I'm playing a skyblock pack so there is no tainted land, preventing normal taint mobs from spawning.

**Comment by ganymedes01** [comment]
If other mobs don't spawn on that biome they probably shouldn't either. So I'll just see how to prevent that from happening :3

**Comment by ganymedes01** [comment]
Fixed it.
Humans should, now, only spawn in biomes that zombies are allowed to spawn
