### ISSUE TITLE
[Suggestion] Turn off ticking on TileEntityBlockSkull

### ISSUE THREAD

**Issue by mikebald** [ganymedes01/Headcrumbs#52]
It doesn't seem like there's a good reason why the TileEntityBlockSkull doesn't override canUpdate() and returns false. Obviously it's not a big deal, but why tick if it's not needed?

**Comment by ganymedes01** [comment]
Indeed. I don't think it will make a difference performance wise but for consistency's sake it should return false on canUpdate()
