### ISSUE TITLE
Request a config option for death spam

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/Headcrumbs#53]
Hello Mate,
Is there anyway to remove the chat spam for 'Blah, Blah was suffocated, pricked to death, burned in lava' etc for head crumbs mobs but leave in the 'Was killed by playerX'?
I couldn't see a config option for it - but I may be blind ;)
Makes it a little confusing on my server.
Cheers,
Me.

*Edit Maybe the spawning rules need tweaking - things seem to die a lot randomly due to the above mentioned things, they may be spawning a bit wonky?

**Comment by ganymedes01** [comment]
It's bot something I add, it's CoFHCore that thought that was a good idea. They have a config option for it though so just turn that off :3

Thr spawning rules are the same as zombies (I think), so I don't know if I'm doing something wrong. I'll have a look :3

(Will you be on skype today? I'll probably pop in later if you fancy a chat)

**Comment by vadis365** [comment]
I may well be about :)
I looked at the code for spawning and I cant see any problems either.
Jeb_Jeb (kiss) seems to suffocate in walls a lot - does she spawn on a mount that puts her head in a block?

**Comment by ganymedes01** [comment]
She spawns on top of a sheep (at her request). That's probably why =P

**Comment by vadis365** [comment]
Should probably do an air check for the blocks above or make her invulnerable to suffocation whilst mounted (would look a bit silly in some cases) ;)

**Comment by ganymedes01** [comment]
Meh, she can continue being derpy. Matches her real-life version more accurately ;D
