### ISSUE TITLE
Grimoire of Gaia 3 compatibility is outdated with GoG 1.2.0+

### ISSUE THREAD

**Issue by karakufire** [ganymedes01/Headcrumbs#56]
Some head textures whose gog mobs are buggy and not attached.

**Comment by ganymedes01** [comment]
Hm, they probably changed the texture paths. I'll update them later. Thanks for letting me know.
Keeping track of all of the supported mod's changes is hard XD

**Comment by ganymedes01** [comment]
The only head I see that is missing the texture is the Minotaurus. Is that correct?

**Comment by karakufire** [comment]
well... what i forgot to say, some mob models are changed(Ex:Werecat's ear place) and add a new mob: kobold.
You should follow changelog of gog wiki. There's all what changed.

**Comment by ganymedes01** [comment]
Ah okay.
Yeah I'll have to check that out then :)

**Comment by karakufire** [comment]
Thank you for update!

**Comment by ganymedes01** [comment]
I think I got them all, but let me know if I've missed anyone :)
