### ISSUE TITLE
[Feature Request] Evil Twins

### ISSUE THREAD

**Issue by Divineaspect** [ganymedes01/Headcrumbs#58]
I would like the ability to, on servers, automatically add everyone who logs on to the Humans list.
As well as a config toggle to determine if your evil twin is trying to kill you as well, or just get others mad at you.

**Comment by ganymedes01** [comment]
A config to make "evil twins" friendly is quite possible.

I'm not quite sure on the first feature though... I'll have to look into it before I can tell you how feasible it is.
