### ISSUE TITLE
EtFuturum Rabbits Cause occasional Server Crash with HeadCrumbs

### ISSUE THREAD

**Issue by BeardlessBrady** [ganymedes01/Headcrumbs#59]
It happens occasionally on my server. Here is my crashlog http://pastebin.com/waXf8rgU

**Comment by ganymedes01** [comment]
ha, I'm calling a method on the server that is only available on the client side... derp =P
Easy to fix though.

A work around to avoid crashes until a fix is released would be to turn off the Et Futurum heads in the config file :)
