### ISSUE TITLE
[Issue] World-ticking

### ISSUE THREAD

**Issue by accessdenied0** [ganymedes01/Headcrumbs#60]
Hey @ganymedes01,

I'm sorry to bother you so close before Christmas but I recently got a issue to report. I'm not sure what caused it, because it crashed very sudden. Here is the [crash report](http://pastebin.com/Yv7THMcP).

thank you for your help,

access_denied

**Comment by ganymedes01** [comment]
Hey, don't worry about it XD
Did you alter the config file in any way? I believe that crash would happen if someone were to delete all the names from the file (which you should never do)

**Comment by accessdenied0** [comment]
Hey @ganymedes01,

sorry for my late answer... I didn't adjust the configs, that why I'm confused... but It didn't happen anymore in the last few times I played. I just took some Wood out of my JABBA-Barrel.

**Comment by buttilda** [comment]
Is this still happening? I haven't been able to reproduce it at all =/

**Comment by accessdenied0** [comment]
So far I can see, no. Strange enough it seem to occur just once...
Even so I thank you for your help :)

I going to close this now, if it occur again, I'll let it you know (with the exact circumstances) but so far I can see It seem to be a ghost in the code... 

access_denied

**Comment by buttilda** [comment]
It might be something I ended up fixing by accident, or an one time only thing caused by a very special set or circumstances. I'll leave it closed, but do let me know if it happens again :)
