### ISSUE TITLE
Skins suddenly stopped working

### ISSUE THREAD

**Issue by vadis365** [ganymedes01/Headcrumbs#61]
2 days before Christmas all headcrumbs skins for player zombies stopped working.
Grimoire of Gaia and Vanilla skins all work and each player can see their own skin on heads and statues but none of the zombie player skins are showing up. Not sure if it is to do with the mod or mojangs skin server?
I'm using version 1.6.2 - I know it may be an older version but it was working fine before :P

**Comment by ganymedes01** [comment]
Is it still not working? Because if it was something momentary it may have been just the mojang servers.

**Comment by vadis365** [comment]
A complete restart of the server and clients seems to have fixed the issue - must have been a server derp or something. All fixied will close. :)
