### ISSUE TITLE
Baby VIP's don't drops heads

### ISSUE THREAD

**Issue by screwnut111** [ganymedes01/Headcrumbs#64]
Since I turned the baby spawn chance to 100, I haven't gotten a single head.

**Comment by buttilda** [comment]
Yeah babies don't drop heads :3

**Comment by screwnut111** [comment]
Ah ok, I didn't think it was intentional as soaryn still drops chests and such thanks. :D

**Comment by buttilda** [comment]
Oh right, yeah that's a bug :3
I'll leave this open so I remember to fix that when I get the chance XD

**Comment by buttilda** [comment]
Fixed in 1.7.4
