### ISSUE TITLE
[1.9.4] [2.0.0] Game is crashing on startup

### ISSUE THREAD

**Issue by Galaxy2Alex** [ganymedes01/Headcrumbs#70]
To make it simple: Game crashes on startup, with the crash report pointing to Headcrumbs.

http://paste.ubuntu.com/17060244/

Any further information will be provided if necessary.

**Comment by buttilda** [comment]
_kicks self_

**Comment by buttilda** [comment]
Thank you for the report. Version 2.0.1 is up on curse waiting for approval :)
