### ISSUE TITLE
Mob heads have no visual effect when worn (1.9.4)

### ISSUE THREAD

**Issue by Cat-McCatface** [ganymedes01/Headcrumbs#71]
What happens: mob head placed on helmet slot is not reflected on player character model. Celeb heads work as intended after they are placed on a wall and broken off to "skin" them.

mod version: 2.0.1
MC: 1.9.4
forge: 1954

**Comment by buttilda** [comment]
Yeah, the mob heads aren't (yet) rendering on players. Forgot to mention that on the changelog.

Do celeb heads only work after you've placed them down and broken them? What happens if you just put them on straight away?

**Comment by Cat-McCatface** [comment]
When a celeb head is obtained from a chest it is default skin (steve/alex) until placed in environment and broken. They can be placed on head and have visual effect but only the default skins.
![2016-06-07_19 40 09](https://cloud.githubusercontent.com/assets/19581414/15879264/2fe11226-2ce8-11e6-9122-0e4946c1423d.png)

**Comment by buttilda** [comment]
I see.
Thank you for your report. I'll look into it :) For now just keep placing them down and breaking them XD
