### ISSUE TITLE
Headcrumbs heads don't work in Ender IO recipies

### ISSUE THREAD

**Issue by ghost** [ganymedes01/Headcrumbs#73]
The Headcrumbs Enderman head can't be used to make the resonant-sentient-ender...it can't be used in the slice and splice. I've found myself with a stack of useless endermen heads.

While it's not the same, it would be great to be able to use Headcrumbs celebrity (zombie) heads for zombie heads.

(Someone else placed a similar request on Curse.)

**Comment by buttilda** [comment]
That used to work in 1.7.10. EnderIO must have changed the ore dictionary name that they use for heads.
I'll need to have a look once I have the time. Thanks for letting me know!
