### ISSUE TITLE
SkyFactory 3 server Crash

### ISSUE THREAD

**Issue by MapleSight** [ganymedes01/Headcrumbs#78]
https://hastebin.com/ufusirakub.vbs
https://hastebin.com/ivavapaweh.sql

These crash logs are totally confusing to me, first one i've seen in this manner. But from the logs I'm ASSUMING it's caused by HeadCrumbs by line 17.

Removed HeadCrumbs, TwitchCrumbs, and WitherCrumbs from the skyfactory 3 server and the issue went away. :P

**Comment by buttilda** [comment]
I see nothing related to Headcrumbs on those logs

**Comment by MapleSight** [comment]
Line 17, first hastebin,  ganymedes01.headcrumbs.utils.ThreadedProfileFiller$1.run(ThreadedProfileFiller.java:24) [ThreadedProfileFiller$1.class:?]

Your mod is the only referenced mod in the entire array of crash logs I had. I removed your mods and the server booted up just fine. No clue whats causing it though, but i'll just keep it removed.
