### ISSUE TITLE
Skyfactory 3.0.6 Server Crash

### ISSUE THREAD

**Issue by LordSkittles** [ganymedes01/Headcrumbs#80]
So my server group and I have been having this issue for a while where a mod was causing HUNDREDS OF THOUSANDS of unnamed threads.... And it would lag the server out.... We couldn't work out what was happening.... Until I shortened the 131816 line server log.... only to find out it was your mod....

Could you please:
1. Name your threads to make it easier to debug
2. Fix this MAJOR issue.

I do understand modding is hard, so you have my sympathies, but I would fix this ASAP. It could cause SERIOUS damage to some computers and systems.

[logs.zip](https://github.com/ganymedes01/Headcrumbs/files/759354/logs.zip)

**Comment by buttilda** [comment]
Could you let me know if this build still has the issue, please:
https://dl.dropboxusercontent.com/u/213747910/Headcrumbs-2.0.2.jar

**Comment by Bolly12321** [comment]
Sorry to bump this but my server is experiencing exactly the same issue on our SF3 server. However we are using Headcrumbs-2.0.3. Any sign of a fix on the matter?

**Comment by TheTurkeyDev** [comment]
I'll have to look into this my self as I do not know what fix, if any, gany came up with.

**Comment by TheTurkeyDev** [comment]
Cleaning out issues. If this issue still persists, please reopen.
