### ISSUE TITLE
[1.10.2] Client crash upon joining

### ISSUE THREAD

**Issue by DeadSix27** [ganymedes01/Headcrumbs#81]
Server does not crash, client does

Stacktrace: http://pastebin.com/WzZ0iYzm

https://github.com/ganymedes01/Headcrumbs/blob/mc1.9/src/main/java/ganymedes01/headcrumbs/entity/EntityHuman.java#L487

**Comment by DeadSix27** [comment]
Seems like its actually caused by Mo' Creatures, as I saw in this persons issue post: https://github.com/DrZhark/mocreatures/issues/39

**Comment by TheTurkeyDev** [comment]
Cleaning out issues. If this issue still persists, please reopen.
