### ISSUE TITLE
(High Priority) Crash Clientside - 1.10.2 During Bloodmoon Event [Created by Lumien]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ganymedes01/Headcrumbs#84]
https://gist.github.com/P3rf3ctXZer0/72c623ee105fb342760259be2b9c2e2c

something to due with spawning

**Comment by P3rf3ctXZer0** [comment]
Also some models do not have skins.

**Comment by TheTurkeyDev** [comment]
Hmmm. Seems you somehow got a mob to spawn without a name. I'll look to see how that happened as well as look into why some players don't have skins.

**Comment by TheBitEffect** [comment]
I also had this problem... I was on a dedicated server. The server ran fine. But anyone who connected crashed. [Crash Report](https://paste.ubuntu.com/25130514/).

**Comment by TheTurkeyDev** [comment]
Cleaning out issues. If this issue still persists, please reopen.
