### ISSUE TITLE
(High Priority) Head Drop rate 1.10.2 Configuration

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ganymedes01/Headcrumbs#85]
Please add a way to increase head drops.

**Comment by Mike-T4** [comment]
I too really miss the configuration option that the 1.7.10 version had.
Only dropping heads with charged creeper explosions kinda sucks since there are mobs that you cannot viably kill this way.

**Comment by TheTurkeyDev** [comment]
This is available in the current version
