### ISSUE TITLE
No players showing up

### ISSUE THREAD

**Issue by thasolidjake** [ganymedes01/Headcrumbs#86]
installed it on my 1.10 server 

and none of the heads are showing up in creative or anything only the mob heads?

**Comment by TheTurkeyDev** [comment]
Player heads have been removed from the creative inventory due to causing lots of lag while loading all of the textures. You can spawn the heads in using the vanilla minecraft command "/give (your name) minecraft:skull 1 3 {SkullOwner: (username)}"
