### ISSUE TITLE
Clarifying possible existing feature

### ISSUE THREAD

**Issue by m1jordanallen** [ganymedes01/Headcrumbs#89]
Currently I am trying to use headcrumbs (version 2.0.3 for 1.10) to spawn exclusively in the end dimension.  I have successfully added dimensions to the blacklist feature, but I am trying to remove the end dimension (dim 1) from the blacklist so they are able to spawn.  By default dim -1 and 1 are on the blacklist.  I am able to remove the dimension from the list, but no spawns happen. 

I believe I read somewhere that certain dimensions are currently hardcoded  "blacklisted" (will not spawn regardless if on the blacklist or not).  I could be wrong, it has been a very long time since configging this mod.  I am wondering if the end dimension is one of these dimensions. 

I dug a very little bit and found a mention of hardcoded blacklist in the code, but as I am very green with java, I couldnt confirm dimensions added to this.  

Before I continue in trying to find some workaround to force spawning into the end for human entities, I figured I would make a slightly more detailed post rather than a twitter post ;)

Thank you for maintaining this mod, it is a personal favorite, regardless of answer :D

**Comment by TheTurkeyDev** [comment]
All I know is that the mobs are registered the same way as most other mobs are from other mods, so if you are/ aren't able to change their spawning around, then it's probably the same for headcrumb mobs
