### ISSUE TITLE
Death config and Nametag drops

### ISSUE THREAD

**Issue by orionSquared** [ganymedes01/Headcrumbs#92]
Just a few questions. Is there a way we can get a config option to turn on and off whether you need a charged creeper or if a head will drop upon kill? Also, are there heads for every single vanilla mob? I ask because the screen shots are (I believe) 1.7.10 and we've had new mobs added, like the evoker, vex, parrot, etc... Just wanna see if those are in there. And does this mod have wither heads? I know the wither has 4 different heads, it'd be awesome if we could get those as well. Lastly, can we get a config that disables the celebrity mobs dropping name tags on death? My inventory gets so full of them lol.

 

Thanks!

**Comment by TheTurkeyDev** [comment]
Should be there in the latest version
