### ISSUE TITLE
1.7.10 - Placing down 2 clay blocks and head won't work

### ISSUE THREAD

**Issue by Gamerbolts** [ganymedes01/Headcrumbs#93]
Hi I was playing around with your mod in my 1.7.10 modpack and placed 2 blocks of clay down and then gave myself a player head with the /headcrumbs command but when I placed the head on top the entire thing went invisible, i could see the outlines with the cursor but nothing else. Not too sure what could be the issue. In the config the option for statues is turned on, and I restarted my game multiple times, same result on both SSP and SMP. Any help is appreciated, thank you

**Comment by Gamerbolts** [comment]
I got a screenshot after placing Captainsparklez head on top of two clay blocks http://imgur.com/a/61Tqv

**Comment by ghost** [comment]
you craft it in a crafting table... Duh

**Comment by TheTurkeyDev** [comment]
Sorry, currently the 1.7.10 version of the mod is no longer being updated.
