### ISSUE TITLE
Issue with custom VIPs

### ISSUE THREAD

**Issue by janagyjr** [ganymedes01/Headcrumbs#95]
I'm trying to add in custom VIPs to my modpack (which will include headcrumbs in next release) but I've had no luck in adding them in the past. The "S:" lines, can they be completely custom? Like

```
    S:namedfield <
      minecraftign
      >
   S:othernamedfield <
        minecraftign2
	>
   S:yetanothernamedfield <
       minecraftign3
	>
```

**Comment by TheTurkeyDev** [comment]
Is this still an issue in the latest versions of the mod?

**Comment by janagyjr** [comment]
To be honest I haven't worked on any modpacks past my 1.7.10 one lately. Once I get the time to do so, I'll be sure to let you know (I'm working on one for 1.10.2 and 1.12.2 which will both include Headcrumbs, fwiw).

**Comment by TheTurkeyDev** [comment]
Cleaning out issues. If this issue still persists, please reopen.
