### ISSUE TITLE
1.10.2 Dedicated Server Threaded Profile Filler NPE

### ISSUE THREAD

**Issue by compwiz1548** [ganymedes01/Headcrumbs#96]
I've been using Headcrumbs on a dedicated server and have noticed a bit of log spam referring to the threaded profile filler. It's not causing any issues as far as I'm aware, but I thought I'd let you know.

Server log: https://gist.github.com/compwiz1548/06b5a41f071a8b65e641a7a2b3ad56df
Headcrumbs config: https://gist.github.com/compwiz1548/be805526fb29e9a4f94f950f184106c6

Mod version: 2.0.3
Forge version: 12.18.3.2488
Minecraft version: 1.10.2

**Comment by TheTurkeyDev** [comment]
Fixed in latest 1.12.2 version
