### ISSUE TITLE
Spam and extreme lag [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [ganymedes01/Headcrumbs#97]
Hi.
Basically your mod throws a lot of spam on the console and generates a lot of lag on the server.
I have sent you the log file for your review.
I am looking forward to your response
regards!

Modpack: SkyFactory 3 (v3.0.15)
Sponge: spongeforge-1.10.2-2477-5.2.0-BETA-2691.jar
HuskyCrates-v1.7.2.jar
HuskyUI-v0.3.1.jar
LuckPerms-Sponge-3.4.20.jar

Full Log: https://pastebin.com/raw/3WX9xtWY

![screenshot_3](https://user-images.githubusercontent.com/13698597/31909938-749fb4a8-b801-11e7-9889-f0d46878808c.png)

**Comment by TheTurkeyDev** [comment]
See #96
